import * as fc from "fast-check";
import { ExtensionRegistry } from "../core/registry.js";
import { deriveSeed } from "../core/seed.js";
import type { JsonValue, Scenario, ScenarioStep } from "../core/types.js";
import { specProfiles } from "../spec/profiles.js";
import type { InspectedSurface } from "../target/surface.js";
import { generateToolArguments } from "./argument-strategies.js";
import type { ArgumentStrategySelection, GeneratorContext, ScenarioGenerator } from "./types.js";

export const generatorNames = [
  "schema-valid",
  "schema-mutated",
  "jsonrpc-envelope",
  "raw-json",
  "sequence",
  "tool-args",
  "resources",
  "prompts",
  "wire-fault",
] as const;

export const generatorRegistry = new ExtensionRegistry<ScenarioGenerator>();

function register(name: string, generator: ScenarioGenerator): void {
  generatorRegistry.register(name, generator);
}

for (const name of generatorNames) {
  register(name, { generate: (context) => generateByName(name, context) });
}

export function generateScenarios(
  revision: GeneratorContext["revision"],
  surface: InspectedSurface,
  seed: number,
  count: number,
  names: readonly string[] = generatorNames,
  transport: GeneratorContext["transport"] = "stdio",
  argumentStrategies?: readonly ArgumentStrategySelection[],
): Scenario[] {
  const available = new Set(generatorRegistry.names());
  const selected = names.filter((name) => available.has(name));
  if (selected.length === 0 || count <= 0) {
    return [];
  }
  const scenarios: Scenario[] = [];
  for (let caseIndex = 0; scenarios.length < count; caseIndex += 1) {
    const name = selected[caseIndex % selected.length];
    if (name === undefined) {
      break;
    }
    const context = {
      seed: deriveSeed(seed, name, String(caseIndex)),
      revision,
      surface,
      caseIndex,
      transport,
      ...(argumentStrategies === undefined ? {} : { argumentStrategies }),
    };
    scenarios.push(generatorRegistry.get(name).generate(context));
  }
  return scenarios;
}

function generateByName(name: (typeof generatorNames)[number], context: GeneratorContext): Scenario {
  const profile = specProfiles.get(context.revision);
  const id = `seed-${context.seed}-${name}-${context.caseIndex}`;
  let steps: ScenarioStep[];
  switch (name) {
    case "schema-valid": {
      const methods = [profile.toolListMethod, profile.resourceListMethod, profile.promptListMethod];
      const method = sample(fc.constantFrom(...methods), context.seed);
      steps = requestSteps(profile, method, `${id}-request`);
      break;
    }
    case "schema-mutated": {
      const request = profile.request("tools/list", `${id}-mutated`);
      steps = [
        { type: "send", message: { ...asObject(request), jsonrpc: "1.0" } },
        { type: "await-response", id: `${id}-mutated`, timeoutMs: 250 },
      ];
      break;
    }
    case "jsonrpc-envelope": {
      const invalidId = `${id}-invalid-envelope`;
      steps = [
        {
          type: "send",
          message: { jsonrpc: "1.0", id: invalidId, method: "fixture/invalid-envelope" },
        },
        { type: "await-response", id: invalidId, timeoutMs: 250 },
        {
          type: "send",
          message: { jsonrpc: "2.0", id: `${id}-unknown`, method: "fixture/unknown-method" },
        },
        { type: "await-response", id: `${id}-unknown`, timeoutMs: 250 },
      ];
      break;
    }
    case "raw-json":
      steps = [
        { type: "send-raw", bytesBase64: Buffer.from("{not-json}\n").toString("base64") },
        ...requestSteps(profile, profile.toolListMethod, `${id}-after-raw`),
      ];
      break;
    case "sequence": {
      const first = profile.request(profile.toolListMethod, `${id}-tools`);
      const second = profile.request(profile.resourceListMethod, `${id}-resources`);
      const third = profile.request(profile.promptListMethod, `${id}-prompts`);
      steps = [first, second, third].flatMap((message) => requestSteps(profile, methodOf(message), idOf(message)));
      break;
    }
    case "tool-args":
      steps = toolCallSteps(context, id);
      break;
    case "resources":
      steps = resourceSteps(context, id);
      break;
    case "prompts":
      steps = promptSteps(context, id);
      break;
    case "wire-fault":
      steps = context.transport === "streamable-http"
        ? httpWireFaultSteps(context, id)
        : wireFaultSteps(context, id);
      break;
  }
  const bootstrap = context.revision === "2026-07-28"
    ? requestSteps(profile, "server/discover", `${id}-discover`)
    : [];
  return {
    formatVersion: 1,
    id,
    specRevision: context.revision,
    description: `Generated by ${name}.`,
    steps: [...profile.lifecycleSteps(`${id}-lifecycle`), ...bootstrap, ...steps],
  };
}

function toolCallSteps(context: GeneratorContext, id: string): ScenarioStep[] {
  const tool = context.surface.tools
    .filter((candidate) => candidate.safety === "read-only")
    .sort((left, right) => left.name.localeCompare(right.name))[0];
  if (tool === undefined) {
    return requestSteps(specProfiles.get(context.revision), "tools/list", `${id}-tools`);
  }
  const argumentsValue = generateToolArguments(tool.name, tool.inputSchema, context.seed, context.argumentStrategies);
  const profile = specProfiles.get(context.revision);
  return requestSteps(profile, "tools/call", `${id}-call`, { name: tool.name, arguments: argumentsValue });
}

function resourceSteps(context: GeneratorContext, id: string): ScenarioStep[] {
  const profile = specProfiles.get(context.revision);
  const resource = [...context.surface.resources].sort((left, right) => left.uri.localeCompare(right.uri))[0];
  if (resource === undefined) {
    return requestSteps(profile, profile.resourceListMethod, `${id}-resources`);
  }
  return requestSteps(profile, "resources/read", `${id}-read`, { uri: resource.uri });
}

function promptSteps(context: GeneratorContext, id: string): ScenarioStep[] {
  const profile = specProfiles.get(context.revision);
  const prompt = [...context.surface.prompts].sort((left, right) => left.name.localeCompare(right.name))[0];
  if (prompt === undefined) {
    return requestSteps(profile, profile.promptListMethod, `${id}-prompts`);
  }
  return requestSteps(profile, "prompts/get", `${id}-get`, { name: prompt.name, arguments: {} });
}

function httpWireFaultSteps(context: GeneratorContext, id: string): ScenarioStep[] {
  const profile = specProfiles.get(context.revision);
  const request = profile.request("tools/list", `${id}-wire`);
  const faults = [
    "missing-accept",
    "missing-content-type",
    "invalid-content-type",
    "missing-protocol-version",
    "mismatched-protocol-version",
    context.revision === "2025-11-25" ? "invalid-session-id" : "wrong-method",
    "truncated-body",
    "oversized-body",
    "abort-response",
    "concurrent-requests",
  ];
  const fault = faults[context.caseIndex % faults.length] ?? faults[0] ?? "missing-accept";
  return [
    {
      type: "send",
      message: request,
      wire: { transport: "streamable-http", fault },
    },
    { type: "await-response", id: `${id}-wire`, timeoutMs: 1_000 },
  ];
}

function wireFaultSteps(context: GeneratorContext, id: string): ScenarioStep[] {
  const profile = specProfiles.get(context.revision);
  const request = profile.request("tools/list", `${id}-wire`);
  const bytes = Buffer.from(`${JSON.stringify(request)}\n`);
  const text = bytes.toString("utf8");
  switch (context.caseIndex % 10) {
    case 0:
      return [{
        type: "send",
        message: request,
        wire: { transport: "stdio", chunks: [1, 2, 3], delayMs: 500 },
      }, { type: "await-response", id: `${id}-wire`, timeoutMs: 1_000 }];
    case 1: {
      const second = profile.request("resources/list", `${id}-wire-second`);
      const coalesced = `${text}${JSON.stringify(second)}\n`;
      return [
        { type: "send-raw", bytesBase64: Buffer.from(coalesced).toString("base64") },
        { type: "await-response", id: `${id}-wire`, timeoutMs: 1_000 },
        { type: "await-response", id: `${id}-wire-second`, timeoutMs: 1_000 },
      ];
    }
    case 2:
      return [
        { type: "send-raw", bytesBase64: Buffer.from(JSON.stringify(request)).toString("base64") },
        { type: "transport", operation: "close-stdin" },
      ];
    case 3:
      return [
        { type: "send-raw", bytesBase64: Buffer.from(`${text}\n`).toString("base64") },
        { type: "await-response", id: `${id}-wire`, timeoutMs: 1_000 },
      ];
    case 4:
      return [
        { type: "send-raw", bytesBase64: Buffer.from(`${JSON.stringify(request)}\r\n`).toString("base64") },
        { type: "await-response", id: `${id}-wire`, timeoutMs: 1_000 },
      ];
    case 5:
      return [
        { type: "send-raw", bytesBase64: Buffer.from([0xff, 0x0a]).toString("base64") },
        ...requestSteps(profile, "tools/list", `${id}-after-binary`),
      ];
    case 6:
      return [
        { type: "send-raw", bytesBase64: Buffer.from(`\uFEFF${text}`).toString("base64") },
        ...requestSteps(profile, "tools/list", `${id}-after-bom`),
      ];
    case 7:
      return [
        { type: "send-raw", bytesBase64: Buffer.from(`${JSON.stringify({ ...asObject(request), padding: "x".repeat(70_000) })}\n`).toString("base64") },
        { type: "await-response", id: `${id}-wire`, timeoutMs: 1_000 },
      ];
    case 8:
      return [
        { type: "send-raw", bytesBase64: Buffer.from(text.slice(0, -2)).toString("base64") },
        { type: "transport", operation: "close-stdin" },
      ];
    default:
      return [
        {
          type: "send",
          message: request,
          wire: { transport: "stdio", chunks: [1], delayMs: 60 },
        },
        { type: "await-response", id: `${id}-wire`, timeoutMs: 1_000 },
      ];
  }
}

function requestSteps(
  profile: ReturnType<typeof specProfiles.get>,
  method: string,
  id: string | number,
  params?: JsonValue,
): ScenarioStep[] {
  return [
    { type: "send", message: profile.request(method, id, params) },
    { type: "await-response", id, timeoutMs: 1_000 },
  ];
}

function sample<T>(arbitrary: fc.Arbitrary<T>, seed: number): T {
  const value = fc.sample(arbitrary, { seed, numRuns: 1 })[0];
  if (value === undefined) {
    throw new Error("Could not sample a value for a generated scenario.");
  }
  return value;
}

function asObject(value: JsonValue): Record<string, JsonValue> {
  return typeof value === "object" && value !== null && !Array.isArray(value) ? value : {};
}

function methodOf(value: JsonValue): string {
  const object = asObject(value);
  return typeof object.method === "string" ? object.method : "unknown";
}

function idOf(value: JsonValue): string | number {
  const object = asObject(value);
  return typeof object.id === "string" || typeof object.id === "number" ? object.id : "generated";
}
