import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const outputDir = join(process.cwd(), "docs");
const outputFile = join(outputDir, "config-reference.md");

const content = `# Configuration reference

This document is generated by \`npm run docs:config\`.

Configuration option reference will be filled in as config schema is implemented in a later milestone.
`;

await mkdir(outputDir, { recursive: true });
await writeFile(outputFile, content, "utf8");
process.stdout.write(`Wrote ${outputFile}\n`);
